### ISSUE TITLE
Build Fails during Installation

### ISSUE THREAD

**Issue by shreyasbapat** [spacetelescope/synphot_refactor#189]
When I am trying to pip install synphot,

```
(testsbpy) [shreyas@canopus ~]$ pip install synphot
Collecting synphot
  Using cached https://files.pythonhosted.org/packages/37/1c/5f1a593827ca7cfc669fbb4d5959e7bef1d9879c2b8ca6ccdd4c93ff9565/synphot-0.1.3.tar.gz
Collecting numpy (from synphot)
  Using cached https://files.pythonhosted.org/packages/bb/76/24e9f32c78e6f6fb26cf2596b428f393bf015b63459468119f282f70a7fd/numpy-1.16.3-cp37-cp37m-manylinux1_x86_64.whl
Collecting astropy (from synphot)
  Using cached https://files.pythonhosted.org/packages/bd/2b/bda134622a5652d884dd5db8362a54f5c2e2dd793d0a4ce24a50880e698e/astropy-3.1.2-cp37-cp37m-manylinux1_x86_64.whl
Building wheels for collected packages: synphot
  Building wheel for synphot (setup.py) ... error
  ERROR: Complete output from command /home/shreyas/testsbpy/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-53bkzum7/synphot/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-6ap0fngi --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/synphot
  copying synphot/version.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/utils.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/units.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/thermal.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/spectrum.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/specio.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/setup_package.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/reddening.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/observation.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/models.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/exceptions.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/docstrings.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/cython_version.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/conftest.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/config.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/compat.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/binning.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/_astropy_init.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/__init__.py -> build/lib.linux-x86_64-3.7/synphot
  creating build/lib.linux-x86_64-3.7/synphot/tests
  copying synphot/tests/test_utils.py -> build/lib.linux-x86_64-3.7/synphot/tests
  copying synphot/tests/test_units.py -> build/lib.linux-x86_64-3.7/synphot/tests
  copying synphot/tests/test_thermal.py -> build/lib.linux-x86_64-3.7/synphot/tests
  copying synphot/tests/test_spectrum.py -> build/lib.linux-x86_64-3.7/synphot/tests
  copying synphot/tests/test_specio.py -> build/lib.linux-x86_64-3.7/synphot/tests
  copying synphot/tests/test_reddening.py -> build/lib.linux-x86_64-3.7/synphot/tests
  copying synphot/tests/test_observation.py -> build/lib.linux-x86_64-3.7/synphot/tests
  copying synphot/tests/test_models.py -> build/lib.linux-x86_64-3.7/synphot/tests
  copying synphot/tests/test_integrator.py -> build/lib.linux-x86_64-3.7/synphot/tests
  copying synphot/tests/test_binning.py -> build/lib.linux-x86_64-3.7/synphot/tests
  copying synphot/tests/setup_package.py -> build/lib.linux-x86_64-3.7/synphot/tests
  copying synphot/tests/__init__.py -> build/lib.linux-x86_64-3.7/synphot/tests
  creating build/lib.linux-x86_64-3.7/synphot/extern
  copying synphot/extern/six.py -> build/lib.linux-x86_64-3.7/synphot/extern
  copying synphot/extern/__init__.py -> build/lib.linux-x86_64-3.7/synphot/extern
  copying synphot/_compiler.c -> build/lib.linux-x86_64-3.7/synphot
  creating build/lib.linux-x86_64-3.7/synphot/src
  copying synphot/src/synphot_utils.c -> build/lib.linux-x86_64-3.7/synphot/src
  copying synphot/src/docstrings.c -> build/lib.linux-x86_64-3.7/synphot/src
  copying synphot/tests/coveragerc -> build/lib.linux-x86_64-3.7/synphot/tests
  creating build/lib.linux-x86_64-3.7/synphot/tests/data
  copying synphot/tests/data/wfc3_ir_g141_src_003_th.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
  copying synphot/tests/data/us7.txt -> build/lib.linux-x86_64-3.7/synphot/tests/data
  copying synphot/tests/data/stis_fuv_f25ndq2_mjd58300_0822774.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
  copying synphot/tests/data/stis_fuv_f25ndq2_binset.bin -> build/lib.linux-x86_64-3.7/synphot/tests/data
  copying synphot/tests/data/qso_template_001.dat -> build/lib.linux-x86_64-3.7/synphot/tests/data
  copying synphot/tests/data/milkyway_diffuse_001.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
  copying synphot/tests/data/k93_4500_0_5_rn_box.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
  copying synphot/tests/data/hst_acs_hrc_f850lp.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
  copying synphot/tests/data/hst_acs_hrc_f555w_x_grw70d5824.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
  copying synphot/tests/data/hst_acs_hrc_f555w.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
  copying synphot/tests/data/grw_70d5824_stisnic_005.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
  copying synphot/tests/data/cos_fuv_g130m_c1309_psa.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-53bkzum7/synphot/setup.py", line 120, in <module>
      **package_info)
    File "/home/shreyas/testsbpy/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/home/shreyas/Softwares/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/shreyas/Softwares/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/shreyas/Softwares/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/shreyas/testsbpy/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/home/shreyas/Softwares/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/shreyas/Softwares/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/shreyas/Softwares/anaconda3/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/shreyas/Softwares/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/shreyas/Softwares/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-53bkzum7/synphot/astropy_helpers/astropy_helpers/commands/build_ext.py", line 296, in run
      np_include = get_numpy_include_path()
    File "/tmp/pip-install-53bkzum7/synphot/astropy_helpers/astropy_helpers/utils.py", line 89, in get_numpy_include_path
      import numpy
  ModuleNotFoundError: No module named 'numpy'
  ----------------------------------------
  ERROR: Failed building wheel for synphot
  Running setup.py clean for synphot
Failed to build synphot
Installing collected packages: numpy, astropy, synphot
  Running setup.py install for synphot ... error
    ERROR: Complete output from command /home/shreyas/testsbpy/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-53bkzum7/synphot/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-__s7s62c/install-record.txt --single-version-externally-managed --compile --install-headers /home/shreyas/testsbpy/include/site/python3.7/synphot:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/synphot
    copying synphot/version.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/utils.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/units.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/thermal.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/spectrum.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/specio.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/setup_package.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/reddening.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/observation.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/models.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/exceptions.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/docstrings.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/cython_version.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/conftest.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/config.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/compat.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/binning.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/_astropy_init.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/__init__.py -> build/lib.linux-x86_64-3.7/synphot
    creating build/lib.linux-x86_64-3.7/synphot/tests
    copying synphot/tests/test_utils.py -> build/lib.linux-x86_64-3.7/synphot/tests
    copying synphot/tests/test_units.py -> build/lib.linux-x86_64-3.7/synphot/tests
    copying synphot/tests/test_thermal.py -> build/lib.linux-x86_64-3.7/synphot/tests
    copying synphot/tests/test_spectrum.py -> build/lib.linux-x86_64-3.7/synphot/tests
    copying synphot/tests/test_specio.py -> build/lib.linux-x86_64-3.7/synphot/tests
    copying synphot/tests/test_reddening.py -> build/lib.linux-x86_64-3.7/synphot/tests
    copying synphot/tests/test_observation.py -> build/lib.linux-x86_64-3.7/synphot/tests
    copying synphot/tests/test_models.py -> build/lib.linux-x86_64-3.7/synphot/tests
    copying synphot/tests/test_integrator.py -> build/lib.linux-x86_64-3.7/synphot/tests
    copying synphot/tests/test_binning.py -> build/lib.linux-x86_64-3.7/synphot/tests
    copying synphot/tests/setup_package.py -> build/lib.linux-x86_64-3.7/synphot/tests
    copying synphot/tests/__init__.py -> build/lib.linux-x86_64-3.7/synphot/tests
    creating build/lib.linux-x86_64-3.7/synphot/extern
    copying synphot/extern/six.py -> build/lib.linux-x86_64-3.7/synphot/extern
    copying synphot/extern/__init__.py -> build/lib.linux-x86_64-3.7/synphot/extern
    copying synphot/_compiler.c -> build/lib.linux-x86_64-3.7/synphot
    creating build/lib.linux-x86_64-3.7/synphot/src
    copying synphot/src/synphot_utils.c -> build/lib.linux-x86_64-3.7/synphot/src
    copying synphot/src/docstrings.c -> build/lib.linux-x86_64-3.7/synphot/src
    copying synphot/tests/coveragerc -> build/lib.linux-x86_64-3.7/synphot/tests
    creating build/lib.linux-x86_64-3.7/synphot/tests/data
    copying synphot/tests/data/wfc3_ir_g141_src_003_th.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
    copying synphot/tests/data/us7.txt -> build/lib.linux-x86_64-3.7/synphot/tests/data
    copying synphot/tests/data/stis_fuv_f25ndq2_mjd58300_0822774.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
    copying synphot/tests/data/stis_fuv_f25ndq2_binset.bin -> build/lib.linux-x86_64-3.7/synphot/tests/data
    copying synphot/tests/data/qso_template_001.dat -> build/lib.linux-x86_64-3.7/synphot/tests/data
    copying synphot/tests/data/milkyway_diffuse_001.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
    copying synphot/tests/data/k93_4500_0_5_rn_box.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
    copying synphot/tests/data/hst_acs_hrc_f850lp.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
    copying synphot/tests/data/hst_acs_hrc_f555w_x_grw70d5824.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
    copying synphot/tests/data/hst_acs_hrc_f555w.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
    copying synphot/tests/data/grw_70d5824_stisnic_005.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
    copying synphot/tests/data/cos_fuv_g130m_c1309_psa.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
    running build_ext
    building 'synphot._compiler' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/synphot
    gcc -pthread -B /home/shreyas/Softwares/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/shreyas/Softwares/anaconda3/include/python3.7m -c synphot/_compiler.c -o build/temp.linux-x86_64-3.7/synphot/_compiler.o
    gcc -pthread -shared -B /home/shreyas/Softwares/anaconda3/compiler_compat -L/home/shreyas/Softwares/anaconda3/lib -Wl,-rpath=/home/shreyas/Softwares/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/synphot/_compiler.o -o build/lib.linux-x86_64-3.7/synphot/_compiler.cpython-37m-x86_64-linux-gnu.so
    /home/shreyas/Softwares/anaconda3/compiler_compat/ld: build/temp.linux-x86_64-3.7/synphot/_compiler.o: unable to initialize decompress status for section .debug_info
    /home/shreyas/Softwares/anaconda3/compiler_compat/ld: build/temp.linux-x86_64-3.7/synphot/_compiler.o: unable to initialize decompress status for section .debug_info
    /home/shreyas/Softwares/anaconda3/compiler_compat/ld: build/temp.linux-x86_64-3.7/synphot/_compiler.o: unable to initialize decompress status for section .debug_info
    /home/shreyas/Softwares/anaconda3/compiler_compat/ld: build/temp.linux-x86_64-3.7/synphot/_compiler.o: unable to initialize decompress status for section .debug_info
    build/temp.linux-x86_64-3.7/synphot/_compiler.o: file not recognized: file format not recognized
    collect2: error: ld returned 1 exit status
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/home/shreyas/testsbpy/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-53bkzum7/synphot/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-__s7s62c/install-record.txt --single-version-externally-managed --compile --install-headers /home/shreyas/testsbpy/include/site/python3.7/synphot" failed with error code 1 in /tmp/pip-install-53bkzum7/synphot/
```

**Comment by pllim** [comment]
I think you have conflicting Python installation. I see

*  /home/shreyas/testsbpy/bin/python 
* /home/shreyas/Softwares/anaconda3/

which suggest that you might have system level Python and Anaconda Python, possibly compiled against different C libraries, and they are conflicting with each other.

My recommendation is that you create a **fresh** conda environment and try pip install from there.

**Comment by shreyasbapat** [comment]
No, I created a virtual environment to show that. Let me show you the output from conda environment! 

```
shreyas@canopus ~> pip install synphot
Collecting synphot
  Using cached https://files.pythonhosted.org/packages/37/1c/5f1a593827ca7cfc669fbb4d5959e7bef1d9879c2b8ca6ccdd4c93ff9565/synphot-0.1.3.tar.gz
Requirement already satisfied: numpy in ./Softwares/anaconda3/lib/python3.7/site-packages (from synphot) (1.16.3)
Requirement already satisfied: astropy in ./Softwares/anaconda3/lib/python3.7/site-packages (from synphot) (3.1.2)
Building wheels for collected packages: synphot
  Building wheel for synphot (setup.py) ... error
  Complete output from command /home/shreyas/Softwares/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-1ksnar7h/synphot/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-yb7o_ajb --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/synphot
  copying synphot/version.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/utils.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/units.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/thermal.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/spectrum.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/specio.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/setup_package.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/reddening.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/observation.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/models.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/exceptions.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/docstrings.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/cython_version.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/conftest.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/config.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/compat.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/binning.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/_astropy_init.py -> build/lib.linux-x86_64-3.7/synphot
  copying synphot/__init__.py -> build/lib.linux-x86_64-3.7/synphot
  creating build/lib.linux-x86_64-3.7/synphot/tests
  copying synphot/tests/test_utils.py -> build/lib.linux-x86_64-3.7/synphot/tests
  copying synphot/tests/test_units.py -> build/lib.linux-x86_64-3.7/synphot/tests
  copying synphot/tests/test_thermal.py -> build/lib.linux-x86_64-3.7/synphot/tests
  copying synphot/tests/test_spectrum.py -> build/lib.linux-x86_64-3.7/synphot/tests
  copying synphot/tests/test_specio.py -> build/lib.linux-x86_64-3.7/synphot/tests
  copying synphot/tests/test_reddening.py -> build/lib.linux-x86_64-3.7/synphot/tests
  copying synphot/tests/test_observation.py -> build/lib.linux-x86_64-3.7/synphot/tests
  copying synphot/tests/test_models.py -> build/lib.linux-x86_64-3.7/synphot/tests
  copying synphot/tests/test_integrator.py -> build/lib.linux-x86_64-3.7/synphot/tests
  copying synphot/tests/test_binning.py -> build/lib.linux-x86_64-3.7/synphot/tests
  copying synphot/tests/setup_package.py -> build/lib.linux-x86_64-3.7/synphot/tests
  copying synphot/tests/__init__.py -> build/lib.linux-x86_64-3.7/synphot/tests
  creating build/lib.linux-x86_64-3.7/synphot/extern
  copying synphot/extern/six.py -> build/lib.linux-x86_64-3.7/synphot/extern
  copying synphot/extern/__init__.py -> build/lib.linux-x86_64-3.7/synphot/extern
  copying synphot/_compiler.c -> build/lib.linux-x86_64-3.7/synphot
  creating build/lib.linux-x86_64-3.7/synphot/src
  copying synphot/src/synphot_utils.c -> build/lib.linux-x86_64-3.7/synphot/src
  copying synphot/src/docstrings.c -> build/lib.linux-x86_64-3.7/synphot/src
  copying synphot/tests/coveragerc -> build/lib.linux-x86_64-3.7/synphot/tests
  creating build/lib.linux-x86_64-3.7/synphot/tests/data
  copying synphot/tests/data/wfc3_ir_g141_src_003_th.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
  copying synphot/tests/data/us7.txt -> build/lib.linux-x86_64-3.7/synphot/tests/data
  copying synphot/tests/data/stis_fuv_f25ndq2_mjd58300_0822774.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
  copying synphot/tests/data/stis_fuv_f25ndq2_binset.bin -> build/lib.linux-x86_64-3.7/synphot/tests/data
  copying synphot/tests/data/qso_template_001.dat -> build/lib.linux-x86_64-3.7/synphot/tests/data
  copying synphot/tests/data/milkyway_diffuse_001.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
  copying synphot/tests/data/k93_4500_0_5_rn_box.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
  copying synphot/tests/data/hst_acs_hrc_f850lp.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
  copying synphot/tests/data/hst_acs_hrc_f555w_x_grw70d5824.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
  copying synphot/tests/data/hst_acs_hrc_f555w.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
  copying synphot/tests/data/grw_70d5824_stisnic_005.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
  copying synphot/tests/data/cos_fuv_g130m_c1309_psa.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
  running build_ext
  building 'synphot._compiler' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/synphot
  gcc -pthread -B /home/shreyas/Softwares/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/shreyas/Softwares/anaconda3/include/python3.7m -c synphot/_compiler.c -o build/temp.linux-x86_64-3.7/synphot/_compiler.o
  gcc -pthread -shared -B /home/shreyas/Softwares/anaconda3/compiler_compat -L/home/shreyas/Softwares/anaconda3/lib -Wl,-rpath=/home/shreyas/Softwares/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/synphot/_compiler.o -o build/lib.linux-x86_64-3.7/synphot/_compiler.cpython-37m-x86_64-linux-gnu.so
  /home/shreyas/Softwares/anaconda3/compiler_compat/ld: build/temp.linux-x86_64-3.7/synphot/_compiler.o: unable to initialize decompress status for section .debug_info
  /home/shreyas/Softwares/anaconda3/compiler_compat/ld: build/temp.linux-x86_64-3.7/synphot/_compiler.o: unable to initialize decompress status for section .debug_info
  /home/shreyas/Softwares/anaconda3/compiler_compat/ld: build/temp.linux-x86_64-3.7/synphot/_compiler.o: unable to initialize decompress status for section .debug_info
  /home/shreyas/Softwares/anaconda3/compiler_compat/ld: build/temp.linux-x86_64-3.7/synphot/_compiler.o: unable to initialize decompress status for section .debug_info
  build/temp.linux-x86_64-3.7/synphot/_compiler.o: file not recognized: file format not recognized
  collect2: error: ld returned 1 exit status
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for synphot
  Running setup.py clean for synphot
Failed to build synphot
Installing collected packages: synphot
  Running setup.py install for synphot ... error
    Complete output from command /home/shreyas/Softwares/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-1ksnar7h/synphot/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-1esubw3u/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/synphot
    copying synphot/version.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/utils.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/units.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/thermal.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/spectrum.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/specio.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/setup_package.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/reddening.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/observation.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/models.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/exceptions.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/docstrings.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/cython_version.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/conftest.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/config.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/compat.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/binning.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/_astropy_init.py -> build/lib.linux-x86_64-3.7/synphot
    copying synphot/__init__.py -> build/lib.linux-x86_64-3.7/synphot
    creating build/lib.linux-x86_64-3.7/synphot/tests
    copying synphot/tests/test_utils.py -> build/lib.linux-x86_64-3.7/synphot/tests
    copying synphot/tests/test_units.py -> build/lib.linux-x86_64-3.7/synphot/tests
    copying synphot/tests/test_thermal.py -> build/lib.linux-x86_64-3.7/synphot/tests
    copying synphot/tests/test_spectrum.py -> build/lib.linux-x86_64-3.7/synphot/tests
    copying synphot/tests/test_specio.py -> build/lib.linux-x86_64-3.7/synphot/tests
    copying synphot/tests/test_reddening.py -> build/lib.linux-x86_64-3.7/synphot/tests
    copying synphot/tests/test_observation.py -> build/lib.linux-x86_64-3.7/synphot/tests
    copying synphot/tests/test_models.py -> build/lib.linux-x86_64-3.7/synphot/tests
    copying synphot/tests/test_integrator.py -> build/lib.linux-x86_64-3.7/synphot/tests
    copying synphot/tests/test_binning.py -> build/lib.linux-x86_64-3.7/synphot/tests
    copying synphot/tests/setup_package.py -> build/lib.linux-x86_64-3.7/synphot/tests
    copying synphot/tests/__init__.py -> build/lib.linux-x86_64-3.7/synphot/tests
    creating build/lib.linux-x86_64-3.7/synphot/extern
    copying synphot/extern/six.py -> build/lib.linux-x86_64-3.7/synphot/extern
    copying synphot/extern/__init__.py -> build/lib.linux-x86_64-3.7/synphot/extern
    copying synphot/_compiler.c -> build/lib.linux-x86_64-3.7/synphot
    creating build/lib.linux-x86_64-3.7/synphot/src
    copying synphot/src/synphot_utils.c -> build/lib.linux-x86_64-3.7/synphot/src
    copying synphot/src/docstrings.c -> build/lib.linux-x86_64-3.7/synphot/src
    copying synphot/tests/coveragerc -> build/lib.linux-x86_64-3.7/synphot/tests
    creating build/lib.linux-x86_64-3.7/synphot/tests/data
    copying synphot/tests/data/wfc3_ir_g141_src_003_th.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
    copying synphot/tests/data/us7.txt -> build/lib.linux-x86_64-3.7/synphot/tests/data
    copying synphot/tests/data/stis_fuv_f25ndq2_mjd58300_0822774.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
    copying synphot/tests/data/stis_fuv_f25ndq2_binset.bin -> build/lib.linux-x86_64-3.7/synphot/tests/data
    copying synphot/tests/data/qso_template_001.dat -> build/lib.linux-x86_64-3.7/synphot/tests/data
    copying synphot/tests/data/milkyway_diffuse_001.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
    copying synphot/tests/data/k93_4500_0_5_rn_box.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
    copying synphot/tests/data/hst_acs_hrc_f850lp.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
    copying synphot/tests/data/hst_acs_hrc_f555w_x_grw70d5824.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
    copying synphot/tests/data/hst_acs_hrc_f555w.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
    copying synphot/tests/data/grw_70d5824_stisnic_005.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
    copying synphot/tests/data/cos_fuv_g130m_c1309_psa.fits -> build/lib.linux-x86_64-3.7/synphot/tests/data
    running build_ext
    building 'synphot._compiler' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/synphot
    gcc -pthread -B /home/shreyas/Softwares/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/shreyas/Softwares/anaconda3/include/python3.7m -c synphot/_compiler.c -o build/temp.linux-x86_64-3.7/synphot/_compiler.o
    gcc -pthread -shared -B /home/shreyas/Softwares/anaconda3/compiler_compat -L/home/shreyas/Softwares/anaconda3/lib -Wl,-rpath=/home/shreyas/Softwares/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/synphot/_compiler.o -o build/lib.linux-x86_64-3.7/synphot/_compiler.cpython-37m-x86_64-linux-gnu.so
    /home/shreyas/Softwares/anaconda3/compiler_compat/ld: build/temp.linux-x86_64-3.7/synphot/_compiler.o: unable to initialize decompress status for section .debug_info
    /home/shreyas/Softwares/anaconda3/compiler_compat/ld: build/temp.linux-x86_64-3.7/synphot/_compiler.o: unable to initialize decompress status for section .debug_info
    /home/shreyas/Softwares/anaconda3/compiler_compat/ld: build/temp.linux-x86_64-3.7/synphot/_compiler.o: unable to initialize decompress status for section .debug_info
    /home/shreyas/Softwares/anaconda3/compiler_compat/ld: build/temp.linux-x86_64-3.7/synphot/_compiler.o: unable to initialize decompress status for section .debug_info
    build/temp.linux-x86_64-3.7/synphot/_compiler.o: file not recognized: file format not recognized
    collect2: error: ld returned 1 exit status
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/shreyas/Softwares/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-1ksnar7h/synphot/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-1esubw3u/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-1ksnar7h/synphot/


```

**Comment by shreyasbapat** [comment]
The conda environment was responsible for this :/ 
Fixed by following this: https://github.com/pytorch/pytorch/issues/16683#issuecomment-459982988
